@startuml
autonumber
activate Alice
Alice -> Bob: Authentifikationsanfrage
activate Bob
Bob -> Alice: Authentifikationsanfrage
activate Alice
Alice -> Alice: Nachricht an "Self"
Alice --> Bob: Authentikationsantwort
deactivate Alice
Bob --> Alice: Authentikationsantwort
deactivate Bob
deactivate Alice
@enduml